on: [push, create]
jobs:
  run-script-to-build-lincity-ng:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - run: nim lincity_ng_build_cmake.nims --archive
      - name: Upload archive
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          name: lincity-ng-package
          path: lincity-ng.zip
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TAG_NAME: ${{ github.ref_name }}
        if: ${{ github.event_name == 'create' && github.ref_type == 'tag'}}
        run: gh release create $env:TAG_NAME lincity-ng.zip
